### PR TITLE
separated electricity demands in output files

### PR DESCRIPTION
**Pull request by gabriel-happle**
- separate output of applicance & lighting demand in all files
(individual buildings & totals)
- separate output of auxiliary (heating, cooling, ventilation, etc)
electricity demand in individual building files ONLY
- script runs

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle please check the last building of the simulation does not work....

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA what is your error exactly? It seems to work for me.

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA could you try again?

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle there are conflicts in the branch, could you take a look at them to make the merge? thanks,

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA I just did an update from master. It solved the problem for me.

**Pull request merged**
