### PR TITLE
I254 optimization to cea

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
This branch implements the resource optimization part of JPLUS (old research work) to the CEA. 

During the process, the demand algoerithm was updated. A new reference case study was also introduced.

steps for testing:
1....get case study of Zug (in the private repository) and copy to C:/

Then run:

2. .../demand/demand_main.py.
3. ... /optimization/optimization_main.py 

Then check after about 20 min that some files be created in the folder..

C:\reference-case-zug\baseline\outputs\data\optimization\master

If so..then it is working....

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas could you please test?

**Comment by daren-thomas** [comment]
cannot run `optimization_main.py`:

- first needed to `pip install deap`. Easy. I added this to the installation guide.
- next, could not find module `cea.optimization.master.master_main` - renamed the file `master_Main.py`
- next, could not find module `cea.optimization.slave.slave_main` - renamed the file `Slave_main.py`
- next error: `ImportError: No module named Python.LayoutData`, the statement was:
```
import cea.optimization.ntwOpt.Python.LayoutData
```
I don't know how to fix that errror. Maybe you forgot to add some files?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas please try again, let me know if the problem persists

**Comment by daren-thomas** [comment]
Ran script. Found files in outputs/data/optimization/master:

- CheckPointInitial
- CheckPoint1
- CheckPoint2
- CheckPoint3
- CheckPoint4

I am merging!

**Pull request merged**
