### PR TITLE
Adding solution for case when V=0

### PR DESCRIPTION
**Pull request by martin-mosteiro**
If the denominator is zero and the numerator isn't, the exponential will tend to zero. However if both are zero an error is raised.

### CODE REVIEW

**Comment by martin-mosteiro** [comment]
After discussion with @gabriel-happle in #583, it was decided there could be a viable case when this error could appear, so the error is fixed in that case.

Also, I found a typo in one formula, which I corrected.

**Comment by daren-thomas** [comment]
@martin-mosteiro why is it failing the tests?

**Comment by daren-thomas** [comment]
@gabriel-happle @JIMENOFONSECA merge? from my side it seems fine...

**Comment by martin-mosteiro** [comment]
@daren-thomas is it?

**Pull request merged**
