### PR TITLE
#672 xls2dbf && dbf2xls

### PR DESCRIPTION
**Pull request by Khayatian**
the required script for adding two tools: xls2dbf and dbf2xls

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro  would you mind being the second pair of eyes in here?

**Comment by martin-mosteiro** [comment]
Can

**Comment by martin-mosteiro** [comment]
Checked the script, seems to work as intended. Really great to have!
Only comment: if the output file has the wrong extension (i.e., neither xls nor dbf), there could be an error message. At the moment it just creates a file that can't be executed.

**Comment by Khayatian** [comment]
tnx for the feedback Martin, will address it.

**Pull request closed without merging**
