### PR TITLE
I662 ciao citygml

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
THis PR request erases compatibility to CityGML in return of symplifying the calculation of Daysim and data exchange.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh could you please take a look at this PR in your computer? you need to run the properties.py to be able to account for windows in different orientations. you can try running radiation_daysim/ radiation_main.y for the open case and the Zug case.

**Comment by shanshanhsieh** [comment]
sure, i will check it out!

**Comment by shanshanhsieh** [comment]
hey @JIMENOFONSECA , i was able to run the open case successfully.
And i noticed that the radiation outputs are stored in `.json` now, could it be read into dataframes like how we read the `.csv` files?
If yes, could you please also modify the `photovoltaic.py` according to the outputs from radiation file?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh done, i changed photovoltaiic.py and it works fine for the open case.

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA i also tested the PV script for both open and zug cases, works great!
however, it gives me an error when running `radiation_main.py` now:

`  File "C:/Users/Shanshan/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_daysim/radiation_main.py", line 210, in radiation_daysim_main
    rad = py2radiance.Rad(daysim_mat, locator)
  File "C:\Users\Shanshan\Anaconda2\envs\cea\lib\site-packages\pyliburo-0.1a8-py2.7.egg\pyliburo\py2radiance\__init__.py", line 36, in __init__
    self.command_file = os.path.join(data_folder_path, "command.txt")
  File "C:\Users\Shanshan\Anaconda2\envs\cea\lib\ntpath.py", line 65, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Users\Shanshan\Anaconda2\envs\cea\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'InputLocator' has no len()`

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh done!, please check thanks!

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA the radiation script is working for the open case and the zug case from my side as well!

**Comment by JIMENOFONSECA** [comment]
@daren-thomas can you help me to know which checks this is not passing? btw, is there a way we can all see the errors of CEAjenkins?

**Comment by daren-thomas** [comment]
The best way is to run `cea test` - that will show you the errors locally. And you can debug them too...

Otherwise... didn't i set up a jenkins login for you? I think I did...

**Comment by daren-thomas** [comment]
@JIMENOFONSECA - the last merge (#675, i612-preprocessing-multiuse-buildings) is where the errors start. Something changed there that breaks the build. This should never have been merged.

**Comment by JIMENOFONSECA** [comment]
I see. I cannot find it, could you set-up for me again and for the whole team? it will be just easier to check directly there what is going on.

thanks,
Jimeno
________________________________

**Comment by JIMENOFONSECA** [comment]
@daren-thomas @martin-mosteiro 

I get this during the tests. what does it mean? did the schedules changed?

11:31:57 GitHub pull request #677 of commit 0cccce092d5d9c097d63d1f62f57b18a668dfe64, no merge conflicts.
11:31:59 Setting status of 0cccce092d5d9c097d63d1f62f57b18a668dfe64 to PENDING with url http://ceajenkins.localtunnel.me/job/Test%20CEA%20Pull%20Requests/522/ and message: 'Build started sha1 is merged.'
11:32:00 Building in workspace C:\Program Files (x86)\Jenkins\workspace\Test CEA Pull Requests
11:32:00 [WS-CLEANUP] Deleting project workspace...
11:32:00 [WS-CLEANUP] Done
11:32:00 Cloning the remote Git repository
11:32:00 Cloning repository https://github.com/architecture-building-systems/CEAforArcGIS
11:32:00  > git.exe init C:\Program Files (x86)\Jenkins\workspace\Test CEA Pull Requests # timeout=10
11:32:00 Fetching upstream changes from https://github.com/architecture-building-systems/CEAforArcGIS
11:32:00  > git.exe --version # timeout=10
11:32:00  > git.exe fetch --tags --progress https://github.com/architecture-building-systems/CEAforArcGIS +refs/heads/*:refs/remotes/origin/*
11:39:29  > git.exe config remote.origin.url https://github.com/architecture-building-systems/CEAforArcGIS # timeout=10
11:39:29  > git.exe config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
11:39:29  > git.exe config remote.origin.url https://github.com/architecture-building-systems/CEAforArcGIS # timeout=10
11:39:29 Cleaning workspace
11:39:29  > git.exe rev-parse --verify HEAD # timeout=10
11:39:29 No valid HEAD. Skipping the resetting
11:39:29  > git.exe clean -fdx # timeout=10
11:39:29 Fetching upstream changes from https://github.com/architecture-building-systems/CEAforArcGIS
11:39:29  > git.exe fetch --tags --progress https://github.com/architecture-building-systems/CEAforArcGIS +refs/pull/*:refs/remotes/origin/pr/*
11:39:34  > git.exe rev-parse "0cccce092d5d9c097d63d1f62f57b18a668dfe64^{commit}" # timeout=10
11:39:34 Checking out Revision 0cccce092d5d9c097d63d1f62f57b18a668dfe64 (detached)
11:39:34  > git.exe config core.sparsecheckout # timeout=10
11:39:34  > git.exe checkout -f 0cccce092d5d9c097d63d1f62f57b18a668dfe64
11:39:35  > git.exe rev-list 9756a2942eb345096b888d86c493e7786babeb37 # timeout=10
11:39:36 [Test CEA Pull Requests] $ cmd /c call C:\Users\darthoma\AppData\Local\Temp\hudson2570378142845747866.bat
11:39:37 
11:39:37 C:\Program Files (x86)\Jenkins\workspace\Test CEA Pull Requests
11:39:37 >set CONDA_DEFAULT_ENV=C:\Users\darthoma\Anaconda\envs\esri104 
11:39:37 
11:39:37 C:\Program Files (x86)\Jenkins\workspace\Test CEA Pull Requests
11:39:37 >set Path=C:\Users\darthoma\Anaconda\envs\esri104;C:\Users\darthoma\Anaconda\envs\esri104\Scripts;C:\Users\darthoma\Anaconda\envs\esri104\Library\bin;C:\Users\darthoma\Anaconda;C:\Users\darthoma\Anaconda\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE;C:\Windows\system32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\cygwin\bin\;C:\Users\darthoma\bin;c:\Users\darthoma\bin\xmlstarlet-1.2.1\;C:\Windows\Microsoft.NET\Framework\v4.0.30319;c:\Program Files (x86)\IronPython 2.7\;C:\Program Files\TortoiseSVN\bin;C:\projects\EnergyPlus\Build\Products\Debug;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\WinMerge;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Calibre2\;C:\Program Files\nodejs\;c:\Users\darthoma\Anaconda\envs\esri104\Lib\site-packages\osgeo;C:\sysinternals;C:\Users\darthoma\AppData\Local\Pandoc\;C:\Program Files (x86)\CMake\bin;C:\Users\darthoma\AppData\Roaming\npm 
11:39:37 
11:39:37 C:\Program Files (x86)\Jenkins\workspace\Test CEA Pull Requests
11:39:37 >set PYTHONPATH=C:\Program Files (x86)\Jenkins\workspace\Test CEA Pull Requests; 
11:39:37 
11:39:37 C:\Program Files (x86)\Jenkins\workspace\Test CEA Pull Requests
11:39:37 >set PYTHONUNBUFFERED=1 
11:39:37 
11:39:37 C:\Program Files (x86)\Jenkins\workspace\Test CEA Pull Requests
11:39:37 >where python 
11:39:37 C:\Users\darthoma\Anaconda\envs\esri104\python.exe
11:39:37 C:\Users\darthoma\Anaconda\python.exe
11:39:37 c:\cygwin\bin\python
11:39:37 
11:39:37 C:\Program Files (x86)\Jenkins\workspace\Test CEA Pull Requests
11:39:37 >python cea\utilities\compile_pyd_files.py 
11:39:37 failed to import from rc_model_sia_cc.pyd, falling back to pure python functions
11:39:37 failed to import from rc_model_sia_cc.pyd, falling back to pure python functions
11:39:38 failed to import from calc_radiator.pyd, falling back to pure python functions
11:39:38 failed to import from calc_radiator.pyd, falling back to pure python functions
11:39:39 failed to import from storagetank_cc.pyd, falling back to pure python functions
11:39:39 failed to import from storagetank_cc.pyd, falling back to pure python functions
11:39:40 
11:39:40 C:\Program Files (x86)\Jenkins\workspace\Test CEA Pull Requests
11:39:40 >python cea\cli.py test --reference-case open 
11:39:45 .  run_unit_tests
11:39:53 ........FF
11:40:18 ======================================================================
11:40:18 FAIL: test_mixed_use_archetype_values (test_schedules.TestBuildingPreprocessing)
11:40:18 ----------------------------------------------------------------------
11:40:18 Traceback (most recent call last):
11:40:18   File "C:\Program Files (x86)\Jenkins\workspace\Test CEA Pull Requests\cea\tests\test_schedules.py", line 40, in test_mixed_use_archetype_values
11:40:18     assert_frame_equal(calculated_results, expected_results)
11:40:18   File "C:\Users\darthoma\Anaconda\envs\esri104\lib\site-packages\pandas\util\testing.py", line 1028, in assert_frame_equal
11:40:18     obj='DataFrame.iloc[:, {0}]'.format(i))
11:40:18   File "C:\Users\darthoma\Anaconda\envs\esri104\lib\site-packages\pandas\util\testing.py", line 925, in assert_series_equal
11:40:18     check_less_precise, obj='{0}'.format(obj))
11:40:18   File "pandas\src\testing.pyx", line 58, in pandas._testing.assert_almost_equal (pandas\src\testing.c:3809)
11:40:18   File "pandas\src\testing.pyx", line 147, in pandas._testing.assert_almost_equal (pandas\src\testing.c:2685)
11:40:18   File "C:\Users\darthoma\Anaconda\envs\esri104\lib\site-packages\pandas\util\testing.py", line 798, in raise_assert_detail
11:40:18     raise AssertionError(msg)
11:40:18 AssertionError: DataFrame.iloc[:, 3] are different
11:40:18 
11:40:18 DataFrame.iloc[:, 3] values are different (100.0 %)
11:40:18 [left]:  [198.75, 231.136363636]
11:40:18 [right]: [208.947368, 236.382979]
11:40:18 
11:40:18 ======================================================================
11:40:18 FAIL: test_mixed_use_schedules (test_schedules.TestScheduleCreation)
11:40:18 ----------------------------------------------------------------------
11:40:18 Traceback (most recent call last):
11:40:18   File "C:\Program Files (x86)\Jenkins\workspace\Test CEA Pull Requests\cea\tests\test_schedules.py", line 80, in test_mixed_use_schedules
11:40:18     reference_results[schedule]))
11:40:18 AssertionError: Schedule 'Qs' at time 3456, 0.000000 != 0.008816
11:40:18 
11:40:18 ----------------------------------------------------------------------
11:40:18 Ran 10 tests in 32.003s
11:40:18 
11:40:18 FAILED (failures=2)
11:40:18 ########################################
11:40:18 TaskFailed - taskid:run_unit_tests
11:40:18 Python Task failed: '<function run_unit_tests at 0x01CAFCB0>' returned False
11:40:18 
11:40:18 read input files
11:40:18 Building B06 has no heating system, Hs corrected to 0.
11:40:18 done
11:40:18 (6192.0, 3216.0)
11:40:18 
11:40:18 
11:40:18 
11:40:18 C:\Program Files (x86)\Jenkins\workspace\Test CEA Pull Requests
11:40:18 >exit 1 
11:40:18 Build step 'Execute Windows batch command' marked build as failure
11:40:18 Setting status of 0cccce092d5d9c097d63d1f62f57b18a668dfe64 to FAILURE with url http://ceajenkins.localtunnel.me/job/Test%20CEA%20Pull%20Requests/522/ and message: ' '
11:40:19 Finished: FAILURE

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro @daren-thomas is it necessary to do an script to create unitest data of the test_schedules.py? could we?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA what changed? it runs in master... I can look into creating a script to create unittest data of the `test_schedules.py`.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas creating unittest data for the test_schedules will be great. The case study in cea/examples changed slightly. So i think this is why there is a problem.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, overwriting your temporary fix with a config file solution. Thanks for clarifying why the data changed - this is important to do when changing the results!

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: now the embodied script is broken - `win_wall` is no longer in the `architecture_df` - it seems this has been moved to a new set of columns `wwr_east`, `wwr_north`, `wwr_west` and `wwr_south`.

(yay! this is a win for the jenkins!)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA the tests still don't run through (run `cea test` on your machine to see what I mean) - it seems mainly the data needs to be regenerate, but I'd like to confirm with you that that is the problem. Why is it suddenly different, when it was working yesterday before your commits?

It looks like your last commit changed the default weather file to singapore. I'm going to change that back. If we do need to change the defaults, could we move that to a separate issue? Also, we could probably do that with the config files - keep the defaults as they are and then let the SN crew use a user config to override the defaults...

**Comment by JIMENOFONSECA** [comment]
@daren-thomas we are ready to merge

**Comment by daren-thomas** [comment]
woohoo! merged! thank you for your hard work on this one, @JIMENOFONSECA!

**Comment by JIMENOFONSECA** [comment]
wihu!….any time :-)!
On 30 Jun 2017, at 3:37 pm, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


woohoo! merged! thank you for your hard work on this one, @JIMENOFONSECA<https://github.com/jimenofonseca>!

**Pull request merged**
