### PR TITLE
235 move weather files to separate directory

### PR DESCRIPTION
**Pull request by daren-thomas**

### CODE REVIEW

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: can we merge this?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas Should not the toolbox be modified to point out to the new folder of the weather files?

**Comment by JIMENOFONSECA** [comment]
working fine

**Comment by daren-thomas** [comment]
I'm pretty sure the `InputLocator` is the only place needed to change. One of the main benefits of using the `InputLocator` :)

**Pull request merged**
