### PR TITLE
I016 thermal loads new ventilation

### PR DESCRIPTION
**Pull request by gabriel-happle**
@JIMENOFONSECA 
@daren-thomas 
@shanshanhsieh 
Can you please test run my branch with the new thermal loads and ventilation calculation procedure?
I will clean up the code meanwhile.

### CODE REVIEW

**Comment by daren-thomas** [comment]
I can successfully run the demand script on this branch. HOWEVER: We cannot merge it at this point. Here are some changes that need to be made:

1. `globalvars.py` imports from `contributions` - this should not be the case
2. the default model (`functions.CalcThermalLoads`) should be the one configured in `globalvars.py`
3. a test-script in the `contributions` folder should show how to use this model (hint: copy `demand.test_demand` to a new script and add a new line after the `gv` instantiation to replace the `calc-thermal-loads` model)
4. this branch breaks the core model: running with `functions.CalcThermalLoads` produces the following error:

```
C:\Users\darthoma\Anaconda2\envs\esri103\python.exe C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/demand.py
reading input files
done
calculating thermal properties
done
creating windows
done
reading occupancy schedules
done
Traceback (most recent call last):
  File "C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/demand.py", line 249, in <module>
    test_demand()
  File "C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/demand.py", line 244, in test_demand
    demand_calculation(locator=locator, weather_path=weather_path, gv=gv)
  File "C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/demand.py", line 82, in demand_calculation
    locator.get_demand_results_folder(), locator.get_temporary_folder())
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\functions.py", line 588, in CalcThermalLoads
    Qhsf = Qhs_sen_loss_true + Qhs_d_ls   # no latent is considered because it is already added as electricity from the adiabatic system.
NameError: global name 'Qhs_sen_loss_true' is not defined

Process finished with exit code 1
```

**Comment by gabriel-happle** [comment]
1) How can this be solved without moving my code to core? I can move to core, but I wasn't sure I if I should...
2) Yes. Absolutely. That is clear. This was simply convenience for you guys to test run my code. I thought this is how your strategy for the "plug-in" functions works.
3) OK.
4) strange bug. Must be from auto refactoring or renaming. Fixed.

**Comment by JIMENOFONSECA** [comment]
So it works fine, but i am afraid it has errors in the calculation of hotwater. We can merge it in contributions. However, we will need to separate it form the hot water calculation and electricity calculation if we want to integrate it in the core

**Comment by gabriel-happle** [comment]
But they are the same as in the core. No changes done to these calculations in that branch.

**Comment by daren-thomas** [comment]
@gabriel-happle, correct: We will need to update the GUI to support using alternative models. I am waiting for the conference to finish before tackling that...

**Comment by daren-thomas** [comment]
how do we proceed here? wait until after the conference?

**Comment by gabriel-happle** [comment]
I don't know. Someone has to decide. I keep it ready by updating from the master every day.
Also, I was waiting for it to be merged until pushing #45  and #53, which change all the versions of CalcThermalLoads.

**Pull request merged**
