### PR TITLE
I643 retrofit analysis

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
this fixes the retrofit analysis option which was erased in the past

### CODE REVIEW

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I like how the error messages give a clue to what is going wrong! But: I can't test this in the reference-case-open: can you provide a combination of options that selects more than 0 buildings?

**Comment by daren-thomas** [comment]
With these options I get a `ValueError: Null layer`:

```
Executing: RetrofitPotentialTool C:\reference-case-open\baseline 2020 false retrofit_HVAC false 15 false 50 false 50 false 4 false 20 false 30 true 0 false 2 false 2 false 2 false 15 false 15 false 15
Start Time: Tue Jul 11 13:34:39 2017
Running script RetrofitPotentialTool...
['C:\\Users\\darthoma\\AppData\\Local\\Temp\\CityEnergyAnalyst\\python.exe', '-u', '-m', 'cea.cli', '--scenario', u'C:\\reference-case-open\\baseline', 'retrofit-potential', '--retrofit-target-date', '2020', '--name', 'retrofit_HVAC', '--heating-costs-threshold', '0']
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\Temp\CityEnergyAnalyst\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\darthoma\AppData\Local\Temp\CityEnergyAnalyst\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\darthoma\documents\github\ceaforarcgis\cea\cli.py", line 452, in <module>
    main()
  File "c:\users\darthoma\documents\github\ceaforarcgis\cea\cli.py", line 448, in main
    parsed_args.func(parsed_args)
  File "c:\users\darthoma\documents\github\ceaforarcgis\cea\cli.py", line 276, in retrofit_potential
    emissions_operation_criteria=args.emissions_operation_threshold)
  File "c:\users\darthoma\documents\github\ceaforarcgis\cea\analysis\retrofit\retrofit_potential.py", line 170, in retrofit_main
    supply, occupancy, data, type_of_join)
  File "c:\users\darthoma\documents\github\ceaforarcgis\cea\analysis\retrofit\retrofit_potential.py", line 185, in retrofit_scenario_creator
    new_geometry.to_file(locator_retrofit.get_building_geometry())
  File "C:\Users\darthoma\AppData\Local\Temp\CityEnergyAnalyst\lib\site-packages\geopandas\geodataframe.py", line 343, in to_file
    to_file(self, filename, driver, schema, **kwargs)
  File "C:\Users\darthoma\AppData\Local\Temp\CityEnergyAnalyst\lib\site-packages\geopandas\io\file.py", line 61, in to_file
    schema=schema, **kwargs) as c:
  File "C:\Users\darthoma\AppData\Local\Temp\CityEnergyAnalyst\lib\site-packages\fiona\__init__.py", line 179, in open
    enabled_drivers=enabled_drivers, crs_wkt=crs_wkt)
  File "C:\Users\darthoma\AppData\Local\Temp\CityEnergyAnalyst\lib\site-packages\fiona\collection.py", line 158, in __init__
    self.session.start(self, **kwargs)
  File "fiona\ogrext.pyx", line 923, in fiona.ogrext.WritingSession.start (fiona/ogrext.c:15860)
ValueError: Null layer

Completed script RetrofitPotentialTool...
Succeeded at Tue Jul 11 13:34:40 2017 (Elapsed Time: 1.10 seconds)
```

(set heating costs threshold to 0)

**Comment by JIMENOFONSECA** [comment]
@fixed! i had to change the open case study for this :-)

**Comment by daren-thomas** [comment]
the bug above has indeed been fixed. i'm merging. good job, @JIMENOFONSECA!

**Pull request merged**
