### PR TITLE
Changing 'DEPO' occupancy to 'PARKING'

### PR DESCRIPTION
**Pull request by martin-mosteiro**
This pull request fixes issue #484

### CODE REVIEW

**Comment by martin-mosteiro** [comment]
@daren-thomas I've updated the ninecubes.zip file as requested. Now it includes a case where a building has 80% parking space and 20% office space.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro did the name of thec schedules database, the archetypes properties and all the cases was changed too?

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Those had all been changed already, I only changed the name of the archetype on one of the scripts which still referred to `DEPO`

**Comment by JIMENOFONSECA** [comment]
Cool

Best, Jimeno

On 3 Mar 2017, at 15:37, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> Those had all been changed already, I only changed the name of the archetype on one of the scripts which still referred to DEPO

**Pull request merged**
