### PR TITLE
I290 pv generation from new radiation script

### PR DESCRIPTION
**Pull request by shanshanhsieh**
A photovoltaic.py script connecting to new radiation calculation results (from Paul) is added to the contribution.
To run the script, please add the example radiation result files to this path: C:\reference-case-zug\baseline\outputs\data\solar-radiation

Link to the example radiation result files: 
https://drive.google.com/folderview?id=0B0xYHrBRUcQoc1ByOHkzQnBXdEk&usp=sharing

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
PV results in null in hours where generation is 0. you might want to see why it is generating null instead of zero.

we might want to add information about the sensors that were selected so later on Paul can map where the PV energy is being taken form and see i the results also are valid.

**Comment by shanshanhsieh** [comment]
Both issues are fixed now.
The ratio_diffhout in the weather data is null when Isol is zero. It is replaced with zeros now, so when Isol is zero, both I_diffuse and I_direct are zero.
Another file, B0000000_sensors.csv, containing metadata of selected sensors is printed. Users could plot the sensors selected with the information in the same file (Zhongming made a grass hopper script to visualize it, it could be included in the plot if necessary).

**Comment by JIMENOFONSECA** [comment]
Great job!

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh you might want to add this as a new issue for the next milestone: adding the PV to the core together with solar radiation and geometry reader from paul..

**Comment by shanshanhsieh** [comment]
done!

**Pull request merged**
