### PR TITLE
I336 add pv script to the core

### PR DESCRIPTION
**Pull request by shanshanhsieh**
New `photovaltaic.py` script that will replace the old one (`photovaltic_arcgis.py`) when the daysim radiation engine is integrated into cea.

To run the photovaltaic.py script, please download the solar-radiation output files from Paul's radiation script here: https://drive.google.com/drive/folders/0B3kdtsWKx4vkS0Q2dk8yeGU0aE0?usp=sharing
The "solar-radiation" folder should be stored at this directory:  `C:\...\baseline\outputs\data\solar-radiation`.
The output examples from `photovaltaic.py`  could be found in "solar_example_outputs" folder.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
We will wait a moment before merging. Until we have the daysim model PR integrated

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh please resolve conflicts

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh would you mind solving conflicts? i would merge this pull request soon

**Comment by shanshanhsieh** [comment]
okay, i will take a look at it tomorrow!

**Comment by shanshanhsieh** [comment]
The check is failing because it requires the changes in pull request #521 , which is adding LIBRARY archetype into the database.... 

Here are the error messages:
.  run_demand:zurich/masterplan@Zurich
########################################
TaskError - taskid:run_demand:zurich/masterplan@Zurich
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "C:\Users\fcl2\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\demand\demand_main.py", line 133, in run_as_script
    demand_calculation(locator=locator, weather_path=weather_path, gv=gv)
  File "C:\Users\fcl2\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\demand\demand_main.py", line 71, in demand_calculation
    schedules = occupancy_model.schedule_maker(date, locator, list_uses)
  File "C:\Users\fcl2\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\demand\occupancy_model.py", line 131, in schedule_maker
    x = pd.read_excel(locator.get_archetypes_schedules(), use).T
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\pandas\io\excel.py", line 170, in read_excel
    skip_footer=skip_footer, converters=converters, **kwds)
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\pandas\io\excel.py", line 372, in _parse_excel
    sheet = self.book.sheet_by_name(asheetname)
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\xlrd\book.py", line 441, in sheet_by_name
    raise XLRDError('No sheet named <%r>' % sheet_name)
XLRDError: No sheet named <u'LIBRARY'>

Running demand calculation for scenario C:\Users\fcl2\AppData\Local\Temp\cea-reference-case\cea-reference-case-master\reference-case-zurich\masterplan
Running demand calculation with weather file C:\Users\fcl2\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\databases\weather\Zurich.epw
read input files
done
Process finished with exit code 2

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh wihU! we have the new engine by paul ready, please check if it works for you. We might need to cross check this PR works... 
how to:
Install Pylibburo of kainwee
Install Daysim 
run
  //resource/radiaton/daysim/create_gml.py
 //resource/radiaton/daysim/radiation_main.py

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh let me know when it is ready for testing and reviewing.

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA  This brach is ready, feel free to test it!

**Pull request merged**
