### PR TITLE
I694 archetype application

### PR DESCRIPTION
**Pull request by martin-mosteiro**
This PR solves #694. A new function is created that generates building architecture properties based on the renovation year of each component rather than only the envelope. It also cleans up redundant functions in the properties.py and emissions.py scripts.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro coudl you check the merging conflicts with master? let me know if there are new things that were changed

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA done

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro please check conflicts, what changes were made to the construction_properties_CH?

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA done
The change is a small correction to `Hs` as discussed in #687.

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle could you test this in your computer? thanks!

**Comment by gabriel-happle** [comment]
It does not pass the dodo on my computer.
The code looks good. But I haven't checked it line by line.

**Comment by martin-mosteiro** [comment]
Weird. Doesn't pass on my computer anymore, either. I'll look into it.

**Comment by martin-mosteiro** [comment]
@daren-thomas, a function you refactored (`calculate_test_mixed_use_archetype_values_results`) is failing:
```
Traceback (most recent call last):
  File "C:\Users\User\Anaconda2\envs\esri104\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
TypeError: calculate_test_mixed_use_archetype_values_results() takes exactly 1 argument (0 given)
```
Any idea why?

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro i believe daren is out for a week. we will have to check this ourselves

**Pull request merged**
