### PR TITLE
fixed error handling. error still get's thrown, but the files do not stay open.

### LINKED ISSUE #244: Scenario plots: When an error occurrs, file stays open
Then the user can't choose the same filename again. Fix the error handling...

### PR DESCRIPTION
**Pull request by daren-thomas**
fixes #244

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro could you please check if this works in your machine?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: BTW, there are no errors. I introduced one in testing (`raise ValueError()`) to make sure that if an error *did* occurr, then it would continue to work.

I saw that you might have been confused by my badly worded commit message above...

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Works fine for me, but I can't check if the issue is solved because the issue starts with "When an error occurs..." BUT given what @daren-thomas just said I guess it's taken care of?

I tried to run the script, open the output file and run the script again with the output file open and I got a reasonable error message `IOError: [Errno 13] Permission denied: 'C:\\Users\\User\\AppData\\Local\\Temp\\scenario_plots.pdf'`

**Comment by daren-thomas** [comment]
The permission denied error can't really be circumvented. This is expected behavior.

**Comment by martin-mosteiro** [comment]
@daren-thomas I know - I was trying to make an error happen to see if the script reacted normally or not.

**Comment by daren-thomas** [comment]
You're my hero! (I forgot to read your message properly and clicked "comment" at the same time as the light bulb went off in my head...)

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: can we merge this?

**Pull request merged**
