### PR TITLE
I171 refactor calcthermalloads

### PR DESCRIPTION
**Pull request by gabriel-happle**

### CODE REVIEW

**Comment by daren-thomas** [comment]
this runs through on my machine! I am going to add the `gv.models` approach we talked about so you have an entry point for your models and then merge the pull...

**Comment by daren-thomas** [comment]
OK. It turns out I can't add the `gv.models` approach we talked about, because: `functions.py` now imports directly from `contributions`. I don't think that is a good idea. Neither does python... what should we do about this? Is the storeage tank part of core?

We need to rethink the folder structure of the project. I would like to postpone this until after the workshop...

**Comment by gabriel-happle** [comment]
But this means that we can not write our own CalcThermalLoad functions for now. I guess we are stuck.

**Comment by daren-thomas** [comment]
thanks @shanshanhsieh & @gabriel-happle, good job!

**Pull request merged**
