### PR TITLE
I9 new radiation engine daysim by paul

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
#9 here it is again with some fixes

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh would you mind taking a look at this PR ? i.e., testing it?. 

To test it
run first create_gml, then run radiation_main in resources/radiation_daysim

@daren-thomas would you mind poiting me to a guide to create the unit tests or whatever is needed for jenkings?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I suggest looking into the file `cea/tests/test_sensible_loads.py` for an easy introduction to unit tests.

If you add a file starting with `test_` into that folder and have a test class inside you're good to go. See https://pymotw.com/2/unittest/ for more information on implementing unit tests. I will hold a presentation on testing philosophy later on, right now I totally need to be on CISBAT...

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA which numpy version do you have? mine is 1.9.2

Here's the error i get:
C:\Users\fcl2\Anaconda2\envs\esri104\python.exe "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/resources/radiation_daysim/create_gml.py"
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
Traceback (most recent call last):
  File "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/resources/radiation_daysim/create_gml.py", line 143, in <module>
    create_citygml(input_buildings_shapefile, input_terrain_raster, output_folder)
  File "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/resources/radiation_daysim/create_gml.py", line 121, in create_citygml
    terrain_face_list = terrain2d23d(citygml_writer, input_terrain)
  File "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/resources/radiation_daysim/create_gml.py", line 94, in terrain2d23d
    raster_points = raster_reader(input_terrain_raster)
  File "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/resources/radiation_daysim/create_gml.py", line 108, in raster_reader
    a = band.ReadAsArray(0, 0, raster_dataset.RasterXSize, raster_dataset.RasterYSize)
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\osgeo\gdal.py", line 1328, in ReadAsArray
    import gdalnumeric
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\osgeo\gdalnumeric.py", line 1, in <module>
    from osgeo.gdal_array import *
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\osgeo\gdal_array.py", line 21, in <module>
    _gdal_array = swig_import_helper()
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\osgeo\gdal_array.py", line 20, in swig_import_helper
    return importlib.import_module('_gdal_array')
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _gdal_array

Process finished with exit code 1

**Comment by JIMENOFONSECA** [comment]
So it might be that you have a version of gdal lacking that.

Check how it was installed and reinstall it..

http://gis.stackexchange.com/questions/82977/is-it-possible-to-use-gdal-without-admin-rights/83297#83297

Best, Jimeno

On 4 Apr 2017, at 18:07, shanshanhsieh <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> which numpy version do you have? mine is 1.9.2

Here's the error i get:
C:\Users\fcl2\Anaconda2\envs\esri104\python.exe "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/resources/radiation_daysim/create_gml.py"
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
Traceback (most recent call last):
File "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/resources/radiation_daysim/create_gml.py", line 143, in
create_citygml(input_buildings_shapefile, input_terrain_raster, output_folder)
File "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/resources/radiation_daysim/create_gml.py", line 121, in create_citygml
terrain_face_list = terrain2d23d(citygml_writer, input_terrain)
File "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/resources/radiation_daysim/create_gml.py", line 94, in terrain2d23d
raster_points = raster_reader(input_terrain_raster)
File "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/resources/radiation_daysim/create_gml.py", line 108, in raster_reader
a = band.ReadAsArray(0, 0, raster_dataset.RasterXSize, raster_dataset.RasterYSize)
File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\osgeo\gdal.py", line 1328, in ReadAsArray
import gdalnumeric
File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\osgeo\gdalnumeric.py", line 1, in
from osgeo.gdal_array import *
File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\osgeo\gdal_array.py", line 21, in
_gdal_array = swig_import_helper()
File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\osgeo\gdal_array.py", line 20, in swig_import_helper
return importlib.import_module('gdal_array')
File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\importlib_init.py", line 37, in import_module
import(name)
ImportError: No module named _gdal_array

Process finished with exit code 1

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA  The previous error was solved by re-install the packages to the following:  `GDAL 2.1.3`, `numpy 1.12.1` and `matplolib 2.0.0` 

Now I am having error with OCC package: 

ERROR:OCC.Display.backend:wx could not be loaded
None

Traceback (most recent call last):
  File "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/resources/radiation_daysim/create_gml.py", line 143, in <module>
    create_citygml(input_buildings_shapefile, input_terrain_raster, output_folder)
  File "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/resources/radiation_daysim/create_gml.py", line 127, in create_citygml
    construct.visualise([terrain_face_list,bsolid_list], ["GREEN","WHITE"],backend = "wx")
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\pyliburo\py3dmodel\construct.py", line 496, in visualise
    display, start_display, add_menu, add_function_to_menu = init_display(backend_str = backend)
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\OCC\Display\SimpleGui.py", line 92, in init_display
    used_backend = load_backend(backend_str)
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\OCC\Display\backend.py", line 209, in load_backend
    raise ValueError(msg)
ValueError: wx could not be loaded

Process finished with exit code 1

**Comment by JIMENOFONSECA** [comment]
no idea... check python occ, you might be missing something in the installation.
________________________________

**Comment by JIMENOFONSECA** [comment]
@daren-thomas the last commit erased the new case study from examples!

**Comment by daren-thomas** [comment]
I moved it back to cea/examples where it was (on master) - this makes it easier to distribute with setuptools... It is not lost, @JIMENOFONSECA!

**Comment by daren-thomas** [comment]
(I'm trying to run all the stuff on my computer, including installing all the dependencies in order to merge this - we're not going back to the old stuff again, right?)

**Comment by JIMENOFONSECA** [comment]
Yes, moving it is fine, just I checked the branch this morning and the folder cea/example was empty. maybe it works now :-)

**Comment by shanshanhsieh** [comment]
@daren-thomas  the folder cea/example seems empty from my side as well (in branch #567

**Comment by JIMENOFONSECA** [comment]
@daren-thomas i think this came back to be urgent now, any chance we could help from here?

**Comment by daren-thomas** [comment]
`cea radiation-daysim` works on my PC:

```
starting Daysim radiation simulation
=======================================================
= gen_dc: calculate direct daylight coefficients      =
= (this simulation may take several minutes to hours) =
=======================================================
calculate 65 direct daylight coefficients for variant static_system...
=======================================================
= gen_dc: calculate diffuse daylight coefficients     =
= (ignore WARNING: no light sources found)            =
= (this simulation may take several minutes to hours) =
=======================================================
calculate diffuse daylight coefficients for variant static_system...
rtrace_dc: warning - no light sources found
ds_illum WARNING: climate file units differ in climate and project header files.
Daysim radiation finished - proceed to save results
execute daysim done
TIME TAKEN:  5.95026666721
```

**BUT:** The following things did pop up:

- the installation guide is not updated to include how to install it (I have updated the `setup.py` file to reflect the pip installable stuff and added the `conda install` magic to the developer's installation section for pythonocc-core, but DAYSIM still needs to be downloaded and installed and I think the guide should explain that)
- the code uses a lot of abbreviations for no purpose whatsoever (`bldng` - seriously? did we run out of bytes??) and what is a `rad_mat`? a radiation matrix? or materials?? I tried to check the docstrings for info but there weren't any.

So. To conclude. We could merge this now. I'm fine with that. Well. I still have to fix the Jenkins... But I would prefer it if we got the code nice and pretty first or at least updated the installation guide.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas when running, it requires to install several libraries. among them OCCUtils, there is an error as conda cannot find it.

**Comment by JIMENOFONSECA** [comment]
do ``conda install -c pythonocc -c oce pythonocc-core==0.17.3`` does not work :-(
image

**Comment by JIMENOFONSECA** [comment]
i checked this, and apperently the problem is with the new version of python 0cc
https://github.com/tpaviot/pythonocc-core/issues/413

**Comment by daren-thomas** [comment]
maybe. hard to say, as they are using different versions (python 3, 64bit as opposed to python2.7, 32bit) but i'll check. I did my testing with miniconda (i like it better as it doesn't add so much stuff to the computer) - i'll also do a check on anaconda. this could take a while: hold yer horses! :)

**Comment by JIMENOFONSECA** [comment]
I fixed it by including another version of python OCC which is the one kianwee refers to in his readme
v 0.16. now it works good

**Comment by daren-thomas** [comment]
I think I figured out how to install the pythonocc. Also pyliburo doesn't need to be installed seperately. I am currently running the daysim radiation in a vm. This could take a while...

**Comment by daren-thomas** [comment]
I have just tested the current installation script in a vm with miniconda. I believe it should also work for anaconda. The following cea commands were tested:

- cea extract-reference-case
- cd  reference-case-open\baseline
- cea data-helper
- cea radiation-daysim
- cea demand

These commands all ran through in a brand-new conda env created with the installation script in my last commit. I needed to track down the os-level loading of dll files using `procmon.exe` to figure out that the problem I was having had to do with `tbb` being installed from `conda-forge`. It needs to be installed from `dlr-sc` as well as `freeimageplus` and `gl2ps`. Next, the `pythonocc` can be installed from the channels `oce` and `pythonocc` at version `0.17.3`. the `python setup.py install` call now installs pyliburo and pythonocc-utils so those do not need to be installed separately.

**Comment by JIMENOFONSECA** [comment]
The installation works fine now, in terms of running the cea test command, i come across the next issues, @daren-thomas any idea how to solve it? 

image

**Pull request merged**
