### PR TITLE
Port to ArcGIS 10.4

### PR DESCRIPTION
**Pull request by daren-thomas**
Test run compares results of running master on ArcGIS 10.3.1 with the HQ reference-case with this branch on ArcGIS 10.4 - identical results.

Did not run Radiation script...

Changes to installation script will be necessary...

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas please check radiation script as this is the one most influenced by the arcpy library. I will check this pull request untill

**Comment by daren-thomas** [comment]
@gabriel-happle: can you try this branch out? You said you would be installing 10.4 this week anyway... There is a branch of the contributors manual with the same name that explains how to install the libraries...

**Comment by daren-thomas** [comment]
I have successfully run the radiation script on this version. It runs through. I would like an independent verification and have asked @gabriel-happle to check it on his machine.

**Comment by daren-thomas** [comment]
@gabriel-happle: I have compared the radiation output from both versions (master vs. this branch) and the output is identical on my machines.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, according to testing from @gabriel-happle and myself, I think this can be merged to master. I was hoping it would be backwards compatible with 10.3.1 but that does not seem to be the case, so we should all update to 10.4.

Please merge this pull request.

**Pull request merged**
