### PR TITLE
I688 fix broken build

### PR DESCRIPTION
**Pull request by martin-mosteiro**
This PR fixes the errors in the unit tests in PR #675, which broke the build.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas can you please check if this fixes the build? @martin-mosteiro did you run the cea test and did it passed? I see it kind of sends 3 warnings. I could not complete the simulation

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA I get three warnings as well, but the tests pass anyway:
```
C:\Users\User\Anaconda2\envs\esri104\python.exe "C:\Program Files
(x86)\JetBrains\PyCharm 2016.3.2\helpers\pycharm\noserunner.py"
C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\tests\
Testing started at 4:23 PM ...

RuntimeError: module compiled against API version 0xa but this version
of numpy is 0x9
RuntimeError: module compiled against API version 0xa but this version
of numpy is 0x9

RuntimeError: module compiled against API version 0xa but this version
of numpy is 0x9
..

..

..

..

..

..

..

..

..

..

----------------------------------------------------------------------
Ran 10 tests in 71.377s

OK

Process finished with exit code 0
```

This, however, was also the case before #675:
```
C:\Users\User\Anaconda2\envs\esri104\python.exe "C:\Program Files (x86)\JetBrains\PyCharm 2016.3.2\helpers\pycharm\noserunner.py" C:\Users\User\Documents\GitHub\CEAforArcGIS\cea\tests\
Testing started at 10:27 AM ...



RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9


RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
..







RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x9
..



..

..



..



..

..



..

----------------------------------------------------------------------
Ran 8 tests in 24.773s

OK


Process finished with exit code 0
```

**Comment by daren-thomas** [comment]
The simulation runs through on my PC. I will make a small change to re-start the Jenkins test. Then we see.

**Comment by daren-thomas** [comment]
OK. we have a problem: The warnings seem to be arising from divisions by zero. Theoretically, `people_per_square_meter` can be zero. As well as the `normalizing_value`.

There might be other instances where a zero can occur... I think this should be fixed. @martin-mosteiro: what should the values be if they aren't set to anything?

**Comment by daren-thomas** [comment]
Also, these two expressions are 0 and lead to a division by 0:

- `internal_loads_DB['Ere_Wm2']['OFFICE']`
- `internal_loads_DB['Ere_Wm2']['INDUSTRIAL']`

**Comment by martin-mosteiro** [comment]
@daren-thomas I removed the divisions by zero you pointed out and redefined the unit tests with a saner structure.

**Pull request merged**
