### PR TITLE
1270 document optimization

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
documenting optimization part for CEA

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh please review the code , thanks..

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA I went through all of the documentation strings for each function to check if I understand the purpose of each function. They all seems clear to me.
I will not go through the naming and inline comments of variables at this point, maybe we will change some along the way. Is that okay for you?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas i think the branch is ready to be merged

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: it doesn't pass the jenkins tests...

You can find out why by running the script `tests/dodo.py` (you might need to `pip install pydoit` first). Sometimes, you need to set `gv.multithreading=False` to get a better error message, but in this case, the error is: 

```
IOError: no such file or directory: 'C:\\Users\\darthoma\\AppData\\Local\\Temp\\Test CEA Pull Requests\\cea-reference-case\\cea-reference-case-master\\reference-case-zug\\decentralized_buildings\\inputs\\building-properties\\occupancy.shp'
```
It seems we made some changes to the input folder structure without updating the reference cases. I'm a big fan of making sure the reference cases are kept up-to-date with the software. Do you have an idea how to fix this?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas i do not recognise the path ....."decentralized_buildings\\inputs\\building-properties\\occupancy.shp" i think it should not be the right one. Somehow the decentralized_buildings folder was introduced without us noticing it.

the reference cases are uptodate in the server

**Comment by daren-thomas** [comment]
huh... that's weird. GitHub thinks it was you who updated the pydoit script (dodo.py) to point to the decentralized-buildings scenario... here: 8eecc048175e7d6c7f11c55709f4979c96839d4a

**Comment by JIMENOFONSECA** [comment]
super weird… i have never used the dodo.py in the first place.

On 25 Nov 2016, at 6:30 pm, Daren Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


huh... that's weird. GitHub thinks it was you who updated the pydoit script (dodo.py) to point to the decentralized-buildings scenario... here: 8eecc04<https://github.com/architecture-building-systems/CEAforArcGIS/commit/8eecc048175e7d6c7f11c55709f4979c96839d4a>

**Comment by daren-thomas** [comment]
super weird... maybe you merged from master and that is how it got there? i'll check. no worried! have a nice weekend!

**Comment by shanshanhsieh** [comment]
hey @daren-thomas, is this branch ready to be merged? it will be great if this branch could be merged before Martin and I start changing the optimization part, thank you!

**Pull request merged**
