### PR TITLE
rename emission.py to operation.py

### PR DESCRIPTION
**Pull request by shanshanhsieh**
1. the emission.py script is renamed as operation.py
2. the non-renewable primary energy demand for operation in total_LCA_operation is named as nre_pen_

### CODE REVIEW

**Comment by shanshanhsieh** [comment]
this branch fixes issue #28

**Comment by martin-mosteiro** [comment]
"the non-renewable primary energy demand for operation in total_LCA_operation is named as nre_pen_"
this should probably also be done for the embodied and mobility scripts, then, based on @amraladdin's feedback, right?

**Comment by martin-mosteiro** [comment]
After feedback from @amraladdin I opened #312 to combine #301 and #306

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh @martin-mosteiro are the names ready to be merged with this branch?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas coudl you check this PR? i will check yours

**Comment by shanshanhsieh** [comment]
as @martin-mosteiro said, this branch will be closed and the changes will be included in branch #312

**Comment by daren-thomas** [comment]
@JIMENOFONSECA it looks like there is nothing left to do.

**Pull request closed without merging**
