### PR TITLE
I633 interface for solar potential

### PR DESCRIPTION
**Pull request by daren-thomas**

### CODE REVIEW

**Comment by shanshanhsieh** [comment]
hey @daren-thomas , could you please adjust one more thing?
that is to run the `radiation.py` before running `photovoltaic.py` if the radiation hasn't been calculated yet.
one way is to check if the `..output/data/solar-radiation` folder is empty.
thanks!

**Comment by daren-thomas** [comment]
hey @shanshanhsieh - I'd prefer to check if the radiation has been run and then tell the user to run radiation first. philosophy time: do one thing - and do that well!

**Comment by shanshanhsieh** [comment]
okay, i agree with your philosophy @daren-thomas  : )
another thing: when i tried to run the solar technology tool from ArcGIS, it was completed, but i wasn't able to find the results. have you checked from your side?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh 

i get the next error

Executing: SolarTechnologyTool C:\reference-case-open\baseline Zug 2014 46.9524055556 7.43958333333 true true 8744 polycrystalline 0.75
Start Time: Wed Jun 21 10:52:56 2017
Running script SolarTechnologyTool...
longitude: 7.43958333333
latitude: 46.9524055556
['C:\\Users\\Jimeno\\Anaconda2\\envs\\cea\\python.exe', '-u', '-m', 'cea.cli', '--scenario', u'C:\\reference-case-open\\baseline', 'photovoltaic', '--latitude', '46.9524055556', '--longitude', '7.43958333333', '--weather-path', 'c:\\users\\jimeno\\documents\\ceaforarcgis\\cea\\databases\\weather\\Zug.epw', '--pvonroof', 'True', '--pvonwall', 'True', '--worst-hour', '8744', '--type-PVpanel', 'PV2', '--min-radiation', '0.75', '--date-start', '2014-01-01']
Traceback (most recent call last):
  File "C:\Users\Jimeno\Anaconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Jimeno\Anaconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\jimeno\documents\ceaforarcgis\cea\cli.py", line 429, in <module>
    main()
  File "c:\users\jimeno\documents\ceaforarcgis\cea\cli.py", line 426, in main
    parsed_args.func(parsed_args)
  File "c:\users\jimeno\documents\ceaforarcgis\cea\cli.py", line 220, in photovoltaic
    date_start=args.date_start)
TypeError: calc_PV() got an unexpected keyword argument 'misc_losses'

Completed script SolarTechnologyTool...
Succeeded at Wed Jun 21 10:52:58 2017 (Elapsed Time: 1.89 seconds)

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA  The error has been resolved!

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh unittests fail here, you might have to update from master

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA done!

**Comment by JIMENOFONSECA** [comment]
I am testing this today

**Comment by shanshanhsieh** [comment]
Hi @JIMENOFONSECA , 
i made the last modifications to this branch, please sync before you continue.
following are the final changes:
- Nothing new was added to the `example` folder, therefore, could be over written by the master branch.
- Delete files polluted from the network branch. (couldn't figure the reason though)
- Modify the calling method for math functions.
- Modify the display message for `weather file` in the interface

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh the script works but I am not sure about the results.

1. The building sensor points do not show the roof surface when I tick the box in the tool.
2. the energy generated of PV seems to not be correct.
-- I checked this by taking form B01_sensors.csv and calculating  total_rad_Wm2*area_netpv_m2/1000 *eff_pv(+-10%) for every sensor for a total of 63000 kWh.
-- I compared the results with the B01_Pv total of the year = 16000 kWh.

Is total_rad_Wm2 something different

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA the issue is resolved. 
The windows surfaces were not removed in the previous script, therefore, resulted in inaccurate calculations.
For B01, the sum of  total_rad_Wm2*area_netpv_m2/1000 *eff_pv(+-10%) for every sensor is 58,841 kWh, whereas, the electricity generated is 56,320 kWh. 

The `total_rad_Whm2` is the reading straight from the radiation calculation, it also includes radiation during the time-steps when the radiation < 50 W/m2. Therefore, if we only look at the sum now, the efficiency is a little bit lower than 10%. But I will prefer to keep the value as it is, because the idea in `B01_sensors.csv` is to show the raw sensor data. What do you think?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh no difference in the results I am getting. did you sync?

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA yes, it was synced 30 mins ago.
I ran the radiation file using `X_DIM: 5` and `Y_DIM: 5`, which generates 893 surfaces (sensors) for B01.
And in `B01_sensors.csv` there are 173 sensors left, with a `area_netpv1 of 636.7 m2.

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA 
1. It is possible to select/un-select the sensors on roofs/walls from the source code now.
2. I cannot figure out which part of the connection goes wrong from the interface when the roofs/walls boxes are unticked. maybe Daren could help us with that.

@daren-thomas , I tried to run the `photovoltaic.py` from the arcgis interface. However, the connection for `pvonroof` and `pvonwall` do not seem to work.
When i un-select `pvonwall`, it is passes `pvonwall` as `False` (as shown in the pic below). However, the argument was not passed to the `calc_PV` function.
It is working when I change inputs in line 798, 799 in `photovoltaic.py` and run it directly from pycharm.
Could you please identify the error? I might change something in `CityEnergyAnalyst.py` or 'cli.py` without noticing.

image
image

**Comment by daren-thomas** [comment]
I get the following error when trying to use the tool:

```
Executing: SolarTechnologyTool C:\reference-case-open\baseline Zug 2014 46.9524055556 7.43958333333 true true 8744 monocrystalline 0.75
Start Time: Tue Jul 11 14:11:13 2017
Running script SolarTechnologyTool...
longitude: 7.43958333333
latitude: 46.9524055556
['C:\\Users\\darthoma\\AppData\\Local\\Temp\\CityEnergyAnalyst\\python.exe', '-u', '-m', 'cea.cli', '--scenario', u'C:\\reference-case-open\\baseline', 'photovoltaic', '--latitude', '46.9524055556', '--longitude', '7.43958333333', '--weather-path', 'c:\\users\\darthoma\\documents\\github\\ceaforarcgis\\cea\\databases\\weather\\Zug.epw', '--pvonroof', 'True', '--pvonwall', 'True', '--worst-hour', '8744', '--type-PVpanel', 'PV1', '--min-radiation', '0.75', '--date-start', '2014-01-01']
reading weather data done
calculating solar properties done
gathering properties of PV panel
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\Temp\CityEnergyAnalyst\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\darthoma\AppData\Local\Temp\CityEnergyAnalyst\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\darthoma\documents\github\ceaforarcgis\cea\cli.py", line 431, in <module>
    main()
  File "c:\users\darthoma\documents\github\ceaforarcgis\cea\cli.py", line 428, in main
    parsed_args.func(parsed_args)
  File "c:\users\darthoma\documents\github\ceaforarcgis\cea\cli.py", line 221, in photovoltaic
    type_PVpanel=args.type_PVpanel, min_radiation=args.min_radiation, date_start=args.date_start)
  File "c:\users\darthoma\documents\github\ceaforarcgis\cea\technologies\photovoltaic.py", line 72, in calc_PV
    filter_low_potential(weather_data, radiation_csv, metadata_csv, min_radiation, pvonroof, pvonwall)
  File "c:\users\darthoma\documents\github\ceaforarcgis\cea\technologies\photovoltaic.py", line 130, in filter_low_potential
    sensors_rad = pd.read_json(radiation_json_path)
  File "C:\Users\darthoma\AppData\Local\Temp\CityEnergyAnalyst\lib\site-packages\pandas\io\json.py", line 281, in read_json
    date_unit).parse()
  File "C:\Users\darthoma\AppData\Local\Temp\CityEnergyAnalyst\lib\site-packages\pandas\io\json.py", line 349, in parse
    self._parse_no_numpy()
  File "C:\Users\darthoma\AppData\Local\Temp\CityEnergyAnalyst\lib\site-packages\pandas\io\json.py", line 566, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None)
ValueError: Expected object or value

Completed script SolarTechnologyTool...
Succeeded at Tue Jul 11 14:11:15 2017 (Elapsed Time: 2.38 seconds)
```

image

**Comment by daren-thomas** [comment]
@shanshanhsieh I fixed the pvonroof/pvonwall issue, though. So once the above is cleared, we can merge.

**Comment by shanshanhsieh** [comment]
Thank you, @daren-thomas ! 
However, I cannot replicate the error above, have you ran the new radiation script?
The new radiation files are saved via `get_radiation_building` in the form of `B09_insolation_Whm2,json` now.
We might have to update the check for whether the radiation has been simulated or not.

**Comment by daren-thomas** [comment]
you're right! i haven't run the new radiation script yet... I just tried, and... i get the dreaded `MemoryError`!

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh I am gonna fix the conflict for you here as it is based in one PR i just did.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh I am getting this error. The daysim radiation script run well.

image

**Comment by shanshanhsieh** [comment]
@daren-thomas do you know what is the cause of this error?
Also, the radiation script, `...radiation_daysim/radiation_main.py`, runs fine on my side.

**Comment by BhargavaKrishnaSreepathi** [comment]
need to connect to the `database\systems\supply_systems.xls`

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh good job!!

**Pull request merged**
