### PR TITLE
Fix errors caused by tank size 0

### PR DESCRIPTION
**Pull request by martin-mosteiro**
As described in #552 , if the tank volume is 0, then the tank surface
area is 0, the tank temperature is equal to nan and Qww_st_ls and Qwwf
are 0.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh could you please review this PR? thanks,

**Comment by shanshanhsieh** [comment]
I tested the script with building functions with no hot water demand: `COOLROOM` , `SCHOOL`, `PARKING`,  `SERVERROOM`.
And this error shows up when the building is a `SERVERROOM`: 

Traceback (most recent call last):
  File "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/demand/demand_main.py", line 144, in <module>
    run_as_script(scenario_path=args.scenario, weather_path=args.weather)
  File "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/demand/demand_main.py", line 133, in run_as_script
    demand_calculation(locator=locator, weather_path=weather_path, gv=gv)
  File "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/demand/demand_main.py", line 83, in demand_calculation
    schedules_dict, weather_data)
  File "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/cea/demand/demand_main.py", line 117, in thermal_loads_all_buildings_multiprocessing
    job.get(240)
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
KeyError: u'T0'

Process finished with exit code 1

any idea why it happens? @martin-mosteiro  @JIMENOFONSECA ?

**Comment by martin-mosteiro** [comment]
@shanshanhsieh I believe this must be connected to issue #560

**Comment by JIMENOFONSECA** [comment]
I think you should run it without multiprocessing to see where the error is..

Best, Jimeno

On 24 Mar 2017, at 16:09, martin-mosteiro <notifications@github.com<mailto:notifications@github.com>> wrote:


@shanshanhsieh<https://github.com/shanshanhsieh> I believe this must be connected to issue #560<https://github.com/architecture-building-systems/CEAforArcGIS/issues/560>

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA 
Without multi-processing, the script works fine for all reference cases as well as building functions without hot water demand: `COOLROOM`, `PARKING`, `SERVERROOM`.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro @shanshanhsieh coudl you clarify in which cases the tank volume is 0? I wonder if there should be always a tank..

**Comment by daren-thomas** [comment]
@shanshanhsieh what is your opinion on this pull request? can we merge it? it *looks* like it should work, but i'd prefer to have it tested.

@martin-mosteiro can you figure out how to add a unit test to test this in future versions? I can help you with this if you like.

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA 'PARKING'?
@daren-thomas Yeah, sure. It'll have to wait for a few days, though.

**Comment by shanshanhsieh** [comment]
@daren-thomas i did not do the unit test, but calculation wise, i think it is good to go : )

**Comment by daren-thomas** [comment]
@shanshanhsieh, check out the files in `cea/tests/test_*.py` they are test suites. Basically, you could create a file `cea/tests/test_552.py` to test the issue #552 - there is a setup part, that you can use to create the scenario to test and then a bunch of functions starting with `test_` that just run code and assert certain properties (like, that a specific error is raised or a certain value was returned from a function call).

The unit test should ideally work at the smallest level possible, so that we can have many many unit tests that don't require simulating a whole scenario - rather test edge cases of functions like `calc_Qww_st_ls`.

I think `cea/tests/test_sensible_loads.py` is probably the best example to look at for inspiration.

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh should we merge this?

**Comment by shanshanhsieh** [comment]
the scripts work fine! but the unit test is not implemented.

**Comment by JIMENOFONSECA** [comment]
based on our past conversation , this might not need unitests

**Comment by shanshanhsieh** [comment]
In this case, this PR is tested and ready to be merged.

**Pull request merged**
