### PR TITLE
updated installation-guide because new pandas version breaks geopandas

### PR DESCRIPTION
**Pull request by daren-thomas**

### CODE REVIEW

**Comment by gabriel-happle** [comment]
Tested new installation guide.
Installation works fine.
Running scripts outputs warnings below.

WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set

**Comment by daren-thomas** [comment]
i'm guessing a previous installation of the gdal stuff is still in your path. do the scripts run through? or does radiation-daysim break in a weird way? (i'm having a similar issue with johannes' pc)

**Comment by JIMENOFONSECA** [comment]
@daren-thomas @gabriel-happle so after solving conflicts it should be ready to be merged right?

**Comment by daren-thomas** [comment]
right. but i'm still waiting for @gabriel-happle to confirm that it works.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I think you can merge it!

**Pull request merged**
