### PR TITLE
I612 preprocessing multiuse buildings

### PR DESCRIPTION
**Pull request by martin-mosteiro**
As discussed in #612, this issue tackles a few different things:
1) Up to now, each building's main use was set the wrong way when most of the building area was of the type 'PARKING'
2) The demands of the building were all set by the building's main use, even in mixed use buildings
3) Schedules did not distinguish the fact that, for example, 10 people working out at a given time do not generate as much humidity gains as 10 people working in an office at the same time

In order to fix these issues, the following was done:
1) Adjust calculation such that if most of the building is used for 'PARKING', the next most common use becomes the main use
2) The archetype values for internal loads, ventilation, heated and electrified are calculated based on an average of the value for each use in the building (rather than being defined for the main use only)
3) Schedules for each type of internal load, ventilation and occupancy are generated for each building based on the schedule database and the mix of uses in the building. these schedules are normalized by the building's archetypal ventilation demands and internal loads such that the building's value can be defined through the corresponding input shapefile while maintaining the demand profile generated by each use type.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle please review this PR, It would need to pass first than #664

**Comment by gabriel-happle** [comment]
@martin-mosteiro and @JIMENOFONSECA I have started testing the functions in the `properties.py`.
Looks good.

**Comment by gabriel-happle** [comment]
If you replace `properties_df[column][building]=...` with `properties_df.loc[building,column]=...` you can get rid of those warnings:

```
C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/demand/preprocessing/properties.py:253: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  properties_df[column][building] = column_total/people_total
C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/demand/preprocessing/properties.py:254: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  else: properties_df[column][building] = 0
C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/demand/preprocessing/properties.py:261: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  properties_df[column][building] = average

```

**Comment by gabriel-happle** [comment]
I checked the detailed reports, e.g. for occupancy and internal humidity gains for some created mixed use buildings in the open case study. It seems to produce the indented results.
I think we can merge.
@martin-mosteiro I think you have to update the calc_thermal_load tests in order to pass and maybe you want to get rid of those warnings. Especially the `RuntimeWarning: invalid value encountered in true_divide` sounds a bit dangerous.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro i believe it works quite well, once it passes the tests we can merge. please connect the PR to an issue. thanks!

**Comment by martin-mosteiro** [comment]
@gabriel-happle, @JIMENOFONSECA thanks for your review, I'll fix these issues today

**Comment by martin-mosteiro** [comment]
The values in the unit test had to be updated since there was an error in the old calculation for water and hot water demand. The thermal loads test now passes on my computer.

**Pull request merged**
