### PR TITLE
Merge remote-tracking branch 'refs/remotes/origin/master' into i406-tabs

### PR DESCRIPTION
**Pull request by martin-mosteiro**
Added comments describing functions and citing the sources for the calculations. Moved hard-coded control temperatures to globalvars. Added my name to every function I wrote.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro this looks like no file was modified.

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA Correct - my changes had mistakenly been done on a different branch. I have now corrected the commits that corresponded to this branch.
@gabriel-happle These are the changes I had discussed with you. Feel free to comment on whether these changes appropriately address the concerns you expressed.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, @martin-mosteiro: I have added some changes to make the code run. I'd prefer not to break my flow today with trying to figure out if it does the proper stuff - maybe you guys can look into that?

**Comment by JIMENOFONSECA** [comment]
merging as it was requested as priority.

**Pull request merged**
