### PR TITLE
I06 archetypes shading fw

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
send @daren-thomas new pull request

### CODE REVIEW

**Comment by daren-thomas** [comment]
jimeno... i can't run emissions.py, because it requires the demand... and that doesn't work anymore?

looks like `Calc_Rf_sh` might have changed? Do you have any idea?

```
>python demand.py
Traceback (most recent call last):
  File "demand.py", line 122, in <module>
    test_demand()
  File "demand.py", line 118, in test_demand
    demand_calculation(locator=locator, gv=gv)
  File "demand.py", line 95, in demand_calculation
    list_uses, T_ext, T_ext_max, RH_ext, T_ext_min, locator.get_temporary_folder(), gv, 0, 0)
  File "C:\projects\CEAforArcGIS\cea\functions.py", line 483, in CalcThermalLoads
    Rf_sh = Calc_Rf_sh(Sh_typ)
  File "C:\projects\CEAforArcGIS\cea\functions.py", line 966, in Calc_Rf_sh
    ValuesRf_Table = pd.DataFrame(d)
  File "C:\Users\darthoma\Anaconda\envs\esri103\lib\site-packages\pandas\core\frame.py", line 201, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "C:\Users\darthoma\Anaconda\envs\esri103\lib\site-packages\pandas\core\frame.py", line 323, in _init_dict
    dtype=dtype)
  File "C:\Users\darthoma\Anaconda\envs\esri103\lib\site-packages\pandas\core\frame.py", line 4548, in _arrays_to_mgr
    index = extract_index(arrays)
  File "C:\Users\darthoma\Anaconda\envs\esri103\lib\site-packages\pandas\core\frame.py", line 4596, in extract_index
    raise ValueError('arrays must all be same length')
ValueError: arrays must all be same length
```

**Comment by JIMENOFONSECA** [comment]
Weird, i just (5 sec ago) run demand and it works all the way through
sync perhaps?
________________________________

**Comment by daren-thomas** [comment]
i think i found the problem: your [archetypes commit](https://github.com/architecture-building-systems/CEAforArcGIS/commit/0bc0fba5f5a71da9a370389c0789df15be09c05b) changed `functions.py` on line 965 to have a different length for `Type` vs. `ValueOUT`.

Can you confirm my last commit, changing `ValueOUT` back to: `[1, 0.08, 0.08, 0.15, 0.57, 0.1]`

**NOTE**: please check the order of the coefficients too...

**Comment by daren-thomas** [comment]
ok. so I have fixed this and will push as soon as github lets me... somehow it doesn't want to let me :(

**Pull request merged**
