### PR TITLE
I526 archetypes singapore

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
@gabriel-happle This is the PR with the archetypes for singapore. After passed it will be required that all case studies in the private repository be updated to that of the cea/examles/reference-case-openp.zip

The databases of archetypes of occupancy and consturction properties are created for singapore. they need to be filled in. I left those spaces in blank.

The column called "standard" denotes C for construction and R for renovation. This is a kind of short term solution to work with standards. BEaware that changing the letter to any other of those two, could brake the embodied.py and  properties.py

### CODE REVIEW

**Comment by gabriel-happle** [comment]
Great. I will fill in the values. Based on the literature collection of #518 #510 #520

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA what does rf_sh in envelope shading systems describe exactly. Most of Singaporean buildings have external shadings. Can we incorporate that?

**Comment by JIMENOFONSECA** [comment]
Check the default databases how to guide in the FAQ section of our website..

Best, Jimeno

On 28 Apr 2017, at 14:37, Gabriel Happle <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> what does rf_sh in envelope shading systems describe exactly. Most of Singaporean buildings have external shadings. Can we incorporate that?

**Comment by JIMENOFONSECA** [comment]
It is a factor that multiplies the amount of solar radiation entering through a window when shades are 'on'. I believe they are on when  Isol>300. See iso 13790 for more info

Best, Jimeno

On 28 Apr 2017, at 15:08, Jimeno Fonseca <fonseca@arch.ethz.ch<mailto:fonseca@arch.ethz.ch>> wrote:

Check the default databases how to guide in the FAQ section of our website..

Best, Jimeno

On 28 Apr 2017, at 14:37, Gabriel Happle <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> what does rf_sh in envelope shading systems describe exactly. Most of Singaporean buildings have external shadings. Can we incorporate that?

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA Thanks for the answer. So the external horizontal and vertical shadings are not part of this. Should they be part of the geometry used for the radiation simulation instead? They are very common in Singapore.
I will assume 'T1' = 'rollo' shading for the Singapore archetypes for now. These seem to be commonly installed (e.g., in CREATE, UWC and my flat)

**Comment by gabriel-happle** [comment]
Tested properties and demand script with Singapore construction archetypes --> no errors.

**Comment by gabriel-happle** [comment]
working on schedules now.
There are actually no schedules defined by ASHRAE 90.1. However, in the [user manual to 90.1](https://www.ashrae.org/resources--publications/bookstore/standard-90-1-user-s-manual) there are standard schedules. They are the same as here: http://www.comnet.org/appendix-c-schedules
The other resource are the schedules of NREL here: http://www.nrel.gov/docs/fy11osti/46861.pdf

**Pull request merged**
