### PR TITLE
Issue 354 CityGML of LOD2.5

### PR DESCRIPTION
**Pull request by shizhongming**
Footprint, roof, wall, window.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@shizhongming could you write a small guide of steps of how to run it in any computer and what are the requiements in terms of software to have installed?

**Comment by JIMENOFONSECA** [comment]
@shizhongming any luck with the small guide?

**Comment by shizhongming** [comment]
@JIMENOFONSECA 
https://docs.google.com/document/d/1nwes6M7eABiYlLMT-P9LXdXk5S1Q-JkmdfRpQ6ebxzo/edit?usp=sharing
Please use this link to have a look at the small instruction..

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle this would be the first step of the CityGML integration, would ou mind checking this PR for me?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas this is breaking the build but i cannot access to the jenkins and the reason of this. Would you mind to shed some light on this?

**Comment by JIMENOFONSECA** [comment]
@shizhongming I checked the file. In order to make possible the use of this CityGML model in CEA. the grasshopper module you created needs to create the Architecture.dbf file of CEA. Please check the example we have on the main repository of CEA. cea/examples/reference-case-open.zip  
let me know if you have questions..

**Comment by daren-thomas** [comment]
@JIMENOFONSECA as far as i can tell the build is not broken anymore :)

**Comment by JIMENOFONSECA** [comment]
great!
________________________________

**Comment by JIMENOFONSECA** [comment]
we close it because citygml will not be used anymore. instead #566 and #665

**Pull request closed without merging**
