### PR TITLE
I648 radaition working

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
This PR makes the new dradiation script workable with big case studies. It improves conmputational time significantly and introduces multi-processing. @gabriel-happle please take a look for the ecocampus case study. I should take about an hour depending on the amount of sensors.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas this should make the Zurich case work. It works in my machine. It has 4 cores and takes 1h 20 min to finish. could you try it in your machine please?

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA you said previously it needs the newest pyliburo version. How can I install it?

**Comment by daren-thomas** [comment]
```
('Error status:', '- Ok')
Files sent to Daysim
Daysim simulation starts
Traceback (most recent call last):
  File "C:\Users\darthoma\AppData\Local\Temp\CityEnergyAnalyst\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\darthoma\documents\github\ceaforarcgis\cea\cli.py", line 377, in main
    parsed_args.func(parsed_args)
  File "c:\users\darthoma\documents\github\ceaforarcgis\cea\cli.py", line 191, in radiation_daysim
    cea.resources.radiation_daysim.radiation_main.main(locator=locator, weather_path=args.weather_path)
  File "c:\users\darthoma\documents\github\ceaforarcgis\cea\resources\radiation_daysim\radiation_main.py", line 467, in main
    radiation_daysim_main(weather_path, locator)
  File "c:\users\darthoma\documents\github\ceaforarcgis\cea\resources\radiation_daysim\radiation_main.py", line 446, in radiation_daysim_main
    if (gv.multiprocessing and mp.cpu_count() > 1):
NameError: global name 'gv' is not defined
```

**Comment by JIMENOFONSECA** [comment]
Hey daren, we identified a kind of in a bottle neck with gabriel. Could you help us to modify the installation so the new pyliburo gets installed? It is needed for this PR.  and it also erases the need of OCCUtils

**Comment by daren-thomas** [comment]
@JIMENOFONSECA it is still running. i didn't install any new pyliburo, just did a `python setup.py develop` - maybe that picked up the newest version already?

**Comment by JIMENOFONSECA** [comment]
@daren-thomas so we get this error when the geometry of a building is not closed, how do we create a message error in arcgis so it tells me that when this error happens the cause can be that the geometry of the building is not closed and that i should close it?

image

**Comment by JIMENOFONSECA** [comment]
so this happens when a shape like this: 

image

creates a cityGML file that is not closed like this:

image

**Comment by JIMENOFONSECA** [comment]
I solved it by moving a bit the wall so it does not create this weird geometry. @gabriel-happle @daren-thomas it shuld now run in your computers, please try it out. The New Version of Pyliburo erases those anoying warnings of OCCUtils and also erases the dependency on OCCUTILS. I suggest @daren-thomas we do the upgrade in the installation to the latest pyliburo in this branch.

image

**Comment by gabriel-happle** [comment]
Great! Thanks for fixing the case study @JIMENOFONSECA. I was not aware of that.
Running the radiation now for EcoCampus and Singapore standard weather file. It's looking good so far.

**Comment by daren-thomas** [comment]
wooohooo!!! it ran through! next on my list: fix the setup.py stuff. then we merge, ok?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: we need a test case, of course. can you single out a minimal case that triggers the error? i can use that to create the error message and build some tests.

**Comment by JIMENOFONSECA** [comment]
out of curiousity, how long did it take? :-)
________________________________

**Comment by daren-thomas** [comment]
It took forever. I didn't time it, but left after more than an hour of waiting and went home (my pc was unusable!)

**Comment by gabriel-happle** [comment]
```Files sent to Daysim
Daysim simulation starts
Using 4 CPU's
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
WARNING:Fiona:GDAL data files not located, GDAL_DATA not set
WARNING:Fiona:PROJ data files not located, PROJ_LIB not set
=======================================================
= gen_dc: calculate direct daylight coefficients      =
= (this simulation may take several minutes to hours) =
=======================================================
calculate 65 direct daylight coefficients for variant static_system...
rtrace_dc: warning - no light sources found
=======================================================
= gen_dc: calculate direct daylight coefficients      =
= (this simulation may take several minutes to hours) =
=======================================================
calculate 65 direct daylight coefficients for variant static_system...
rtrace_dc: warning - no light sources found
=======================================================
= gen_dc: calculate direct daylight coefficients      =
= (this simulation may take several minutes to hours) =
=======================================================
calculate 65 direct daylight coefficients for variant static_system...
rtrace_dc: warning - no light sources found
=======================================================
= gen_dc: calculate diffuse daylight coefficients     =
= (ignore WARNING: no light sources found)            =
= (this simulation may take several minutes to hours) =
=======================================================
calculate diffuse daylight coefficients for variant static_system...
=======================================================
= gen_dc: calculate diffuse daylight coefficients     =
= (ignore WARNING: no light sources found)            =
= (this simulation may take several minutes to hours) =
=======================================================
calculate diffuse daylight coefficients for variant static_system...
Process Process-3:
Traceback (most recent call last):
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\resources\radiation_daysim\radiation_main.py", line 313, in isolation_daysim
    solar_res = rad.eval_ill_per_sensor()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pyliburo\py2radiance\__init__.py", line 717, in eval_ill_per_sensor
    res_dict_list = self.eval_ill()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pyliburo\py2radiance\__init__.py", line 709, in eval_ill
    resultlist_f.append(float(r))
MemoryError
=======================================================
= gen_dc: calculate diffuse daylight coefficients     =
= (ignore WARNING: no light sources found)            =
= (this simulation may take several minutes to hours) =
=======================================================
calculate diffuse daylight coefficients for variant static_system...
Process Process-5:
Traceback (most recent call last):
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\resources\radiation_daysim\radiation_main.py", line 313, in isolation_daysim
    solar_res = rad.eval_ill_per_sensor()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pyliburo\py2radiance\__init__.py", line 717, in eval_ill_per_sensor
    res_dict_list = self.eval_ill()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pyliburo\py2radiance\__init__.py", line 709, in eval_ill
    resultlist_f.append(float(r))
MemoryError
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\resources\radiation_daysim\radiation_main.py", line 313, in isolation_daysim
    solar_res = rad.eval_ill_per_sensor()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pyliburo\py2radiance\__init__.py", line 717, in eval_ill_per_sensor
    res_dict_list = self.eval_ill()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pyliburo\py2radiance\__init__.py", line 709, in eval_ill
    resultlist_f.append(float(r))
MemoryError
=======================================================
= gen_dc: calculate direct daylight coefficients      =
= (this simulation may take several minutes to hours) =
=======================================================
calculate 65 direct daylight coefficients for variant static_system...
rtrace_dc: warning - no light sources found
=======================================================
= gen_dc: calculate direct daylight coefficients      =
= (this simulation may take several minutes to hours) =
=======================================================
calculate 65 direct daylight coefficients for variant static_system...
rtrace_dc: warning - no light sources found
=======================================================
= gen_dc: calculate diffuse daylight coefficients     =
= (ignore WARNING: no light sources found)            =
= (this simulation may take several minutes to hours) =
=======================================================
calculate diffuse daylight coefficients for variant static_system...
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\resources\radiation_daysim\radiation_main.py", line 313, in isolation_daysim
    solar_res = rad.eval_ill_per_sensor()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pyliburo\py2radiance\__init__.py", line 717, in eval_ill_per_sensor
    res_dict_list = self.eval_ill()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pyliburo\py2radiance\__init__.py", line 709, in eval_ill
    resultlist_f.append(float(r))
MemoryError
=======================================================
= gen_dc: calculate diffuse daylight coefficients     =
= (ignore WARNING: no light sources found)            =
= (this simulation may take several minutes to hours) =
=======================================================
calculate diffuse daylight coefficients for variant static_system...
Process Process-4:
Traceback (most recent call last):
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\resources\radiation_daysim\radiation_main.py", line 313, in isolation_daysim
    solar_res = rad.eval_ill_per_sensor()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pyliburo\py2radiance\__init__.py", line 717, in eval_ill_per_sensor
    res_dict_list = self.eval_ill()
  File "C:\Users\Gabriel\Anaconda2\envs\cea\lib\site-packages\pyliburo\py2radiance\__init__.py", line 709, in eval_ill
    resultlist_f.append(float(r))
MemoryError
Daysim simulation finished in  158.936533332  mins
Daysim simulation finished in  163.908716667  mins

Process finished with exit code 0
```

**Comment by gabriel-happle** [comment]
@JIMENOFONSECA I can't run the arcgis radiation either:

```C:\Users\Gabriel\Anaconda2\envs\cea\python.exe C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py
PyTables is not installed. No support for HDF output.
C:\Users\Gabriel\Documents\GitHub\CEAforArcGIS\cea\databases\weather\Singapore.epw
complete calculating sunrise
Traceback (most recent call last):
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 508, in <module>
    longitude=args.longitude, year=args.year)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 493, in run_as_script
    weather_path=weather_path)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 97, in solar_radiation_vertical
    Burn(Simple_context, locator.get_terrain(), dem_rasterfinal, locator.get_temporary_folder(), dem_raster_extent, gv)
  File "C:/Users/Gabriel/Documents/GitHub/CEAforArcGIS/cea/resources/radiation_arcgis/radiation.py", line 455, in Burn
    RadiationDEM.save(DEMfinal)
RuntimeError: ERROR 010240: Could not save raster dataset to C:\Users\Gabriel\Documents\ArcGIS\Default.gdb\DEM_All2 with output format FGDBR.

Process finished with exit code 1```

But I do have the specified `Default.gdb`:
![image](https://cloud.githubusercontent.com/assets/17002288/26350952/f9b4d6c4-3fe7-11e7-98b0-22debb8082ae.png)

**Comment by daren-thomas** [comment]
works here - i'd like to merge?

**Pull request merged**
