### PR TITLE
I055 floor heating model

### PR DESCRIPTION
**Pull request by martin-mosteiro**
Same as reported for i53 pull request, the results look consistent, but full testing cannot be undertaken until #293  is solved

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
I CAN GET IT AFTER #293

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro could you check the plots, and results by running graphs.py and demands.py from the source. We have to update from master in order to do that

**Comment by martin-mosteiro** [comment]
I did. The graphs look pretty consistent with previous demand graphs.

**Comment by daren-thomas** [comment]
PR sent to fix #293 - check out #302...

**Comment by JIMENOFONSECA** [comment]
working nicely..

**Pull request merged**
