### PR TITLE
add schedule of Library

### PR DESCRIPTION
**Pull request by shanshanhsieh**
The occupancy schedule of Library is added to the archetypes database. referring to issue #521

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh this PR might require:
1. Adding the 'library' use to all the case studies. (a new column in the occupancy.shp called "LIBRARY")
2. checking that properties.py work with this.
3. adding to the l variable of uses in globalvariables.py  "LIBRARY"

**Comment by shanshanhsieh** [comment]
sure, i am on it!

**Comment by shanshanhsieh** [comment]
hey @JIMENOFONSECA here are some questions:
 
1&2. I was able to add a new field to the `occupancy.shp`, and assigned the cell type as "double".  But the values in the new field show up as `None` instead of numbers when I read it from the `property.py` script... Please let me know if i am missing out some crucial steps.

3. I did not understand this one, the `property` function is not calling anything from `globalvariables.py` except for the scenario.

**Comment by JIMENOFONSECA** [comment]
The property script does not change the field in occupancy.shp. The occupancy.shp is an user input.



________________________________

**Comment by gabriel-happle** [comment]
This shows how the Excel Databases are not really dynamic. It should be possible to change databases without changing the code. @daren-thomas can not the shape file reader create new usages, i.e. add stuff to globalvars, etc?

**Comment by shanshanhsieh** [comment]
Yes, as far as I understand, a new field called "LIBRARY" should be added to `occupancy.shp` as a new input.
I tried to edit `occupancy.shp` accordingly, but the problem is the values in the new field showed up as `None` instead of numbers when I read it from the property.py script...

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA  After editing the values through 3D Editor in ArcScene, the values in the new field can be read from `property.py` now. But the process is not so straightforward. Maybe you could show me an easier way to do this on Monday?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh do you still need assistance in it?

**Comment by JIMENOFONSECA** [comment]
I changed the reference cases to include LIBRARY in occupancy.shp

**Comment by JIMENOFONSECA** [comment]
waiting for the archetypes to be ready

**Comment by shanshanhsieh** [comment]
These are the error messages I got from running dodo.py, @daren-thomas maybe you could help me to understand this? thanks!

`C:\Users\fcl2\Anaconda2\envs\esri104\python.exe "C:/Users/fcl2/AppData/Roaming/ESRI/Desktop10.4/ArcToolbox/My Toolboxes/tests/dodo.py"
.  download_reference_cases
.  run_data_helper:zug/baseline
.  run_data_helper:zurich/masterplan
.  run_data_helper:open
.  run_data_helper:zurich/baseline
.  download_radiation:zug/baseline
.  download_radiation:zurich/masterplan
.  download_radiation:open
.  download_radiation:zurich/baseline
.  run_demand:zug/baseline@Zug
.  run_demand:zurich/masterplan@Zurich
########################################
TaskError - taskid:run_demand:zurich/masterplan@Zurich
PythonAction Error
Traceback (most recent call last):
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\site-packages\doit\action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "C:\Users\fcl2\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\demand\demand_main.py", line 133, in run_as_script
    demand_calculation(locator=locator, weather_path=weather_path, gv=gv)
  File "C:\Users\fcl2\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\demand\demand_main.py", line 83, in demand_calculation
    schedules_dict, weather_data)
  File "C:\Users\fcl2\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\demand\demand_main.py", line 117, in thermal_loads_all_buildings_multiprocessing
    job.get(240)
  File "C:\Users\fcl2\Anaconda2\envs\esri104\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

Running demand calculation for scenario C:\Users\fcl2\AppData\Local\Temp\cea-reference-case\cea-reference-case-master\reference-case-zurich\masterplan
Running demand calculation with weather file C:\Users\fcl2\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\databases\weather\Zurich.epw
read input files
done
Using 8 CPU's



Process finished with exit code 2`

**Comment by JIMENOFONSECA** [comment]
merging as we need it urgently to run master

**Pull request merged**
