### PR TITLE
fixes #293 (Full reports not working with tsd as dict)

### LINKED ISSUE #293: Full reports not working with "tsd" as dict
The option for full reporting does not work any more for `tsd` variable as `dict`.

### PR DESCRIPTION
**Pull request by daren-thomas**
There are some variables that are not being reported:

- cannot report following variables: q_int, Eal_nove, Edata, vww, vw, Qcdata, Qcrefri, Hve, Htr_is, Htr_ms, Htr_w, Htr_em, Htr_1, Htr_2, Htr_3, QHC_sen, t5, tHset_corr, tCset_corr, Waterconsumption
- cannot report following variables: Name, Af, Aef, sys_e_heating, sys_e_cooling, Am, Atot, Awall_all, Cm, Ll, Lw, Retrofit, Sh_typ, Year, footprint, nf_ag, nfp, Lcww_dis, Lsww_dis, Lv, Lvww_dis, Tcs_re_0, Tcs_sup_0, Ths_re_0, Ths_sup_0, Tww_re_0, Tww_sup_0, Y, fforma

But this is just info the reporting function produces when the reporting template in `GlobalVariables` is not set up properly. That is a separate issue.

### CODE REVIEW

**Comment by daren-thomas** [comment]
@JIMENOFONSECA, this should be trivial to check. There are some other pull requests / issues waiting for this to happen, so maybe prio 1?

**Comment by JIMENOFONSECA** [comment]
image

**Comment by daren-thomas** [comment]
Could you turn off multiprocessing and see if it runs through? Next, on line 156 of `demand_main.py`, you can increase the timeout: job.get(60) -> job.get(120)

Maybe your computer doesn't have SSD, so writing out the reporting files increases the time to to simulate. That would explain the error message.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA: Please try again - I went ahead and pushed the fix I proposed above...

**Pull request merged**
