### PR TITLE
441 create call graph

### PR DESCRIPTION
**Pull request by daren-thomas**
Creates the call graphs mentioned in #441 at the function and module level.

(The function level is waaay too detailed to show in the documentation but interesting in its own right, the module level graph hints at some refactorings that could be made...)

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
how do it test it?:-) @daren

**Comment by JIMENOFONSECA** [comment]
One question, does it allow to check also variables and running time? I came across the module pycallgraph which could be useful for this, is it different?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA maybe wait a bit first. I will add more documentation but I'm still working on some interesting aspects of this technology.

You can use the batch files in the `bin` folder to run it.

**Comment by daren-thomas** [comment]
pycallgraph is cool. I used the same technique but don't check running time or variables (waaay too much information to store). Checking running time if you're doing tracing doesn't really work anyway, since the tracing adds a big overhead. This needs to be done with a profiler instead.

**Comment by JIMENOFONSECA** [comment]
@daren-thomas thanks, cool stuff.

**Comment by daren-thomas** [comment]
@JIMENOFONSECA How to test this:

- check out the `bin` folder: There are two `.bat` files that each produce a pdf. 
  - The documentation in those files point out that you need to install GraphViz in order to produce the files - this is an easy-to-install program
- there is an ipython notebook in the `bin` folder that shows a more programmatic use of the `create_function_graph` module to filter out calls to `InputLocator` for documenting input- and output-files to our scripts.
  - output was manually processed to produce the file `docs/module_input_and_output_files.md` that can later be incorporated into the documentation somehow.

**Pull request merged**
