### PR TITLE
I297 tabs temperature

### PR DESCRIPTION
**Pull request by martin-mosteiro**
Finally bothered to fix the temperature calculation...

### CODE REVIEW

**Comment by daren-thomas** [comment]
who is the best person to review these changes? I have had a quick look, but I think it would be better if we had some domain knowledge here...

@gabriel-happle? @JIMENOFONSECA?

**Comment by daren-thomas** [comment]
Please don't merge yet: I am making some (cosmetic) changes.

**Comment by daren-thomas** [comment]
@martin-mosteiro : could you provide a calculation example (unit test) for the tabs module? we can work on this together if you like... are any buildings in the three reference cases using the tabs module?

**Comment by martin-mosteiro** [comment]
I tested it by creating new scenarios where every building was heated with TABS. Nonetheless, the following buildings from the Zurich baseline scenario use TABS:

- B302019753
- B302019754
- B302019755
- B302020926
- B302030670
- B302030671
- B302030556
**- B302021377
- B302024465**
- B302030047

Out of these, only the ones in bold are within the zone of study.

**Comment by daren-thomas** [comment]
This branch can now be merged. Martin and I will add some unit tests as an example of how we should be testing models in the future, but the branch can be merged before that.

**Pull request merged**
