### PR TITLE
changes to getting started documentation

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**
The latest folder structure is included and described. the workflow too.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@daren-thomas I imagine the diagram of the workflow needs to change somehow... would you mind checking on this?

**Comment by daren-thomas** [comment]
@JIMENOFONSECA I'm not sure what you mean...

**Comment by JIMENOFONSECA** [comment]
@daren-thomas in the getting started.srt i found a diagram explaining a workflow. I wonder if it is still valid based on the description i made

**Comment by daren-thomas** [comment]
@JIMENOFONSECA can you please merge this? This fixes the **readthedocs.io** build! finally!

**Pull request merged**
