### PR TITLE
I-318 - timeseries interactive graphs

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle coudl you check if it works in your machine? you could run timeseries_interactive_graph.py. 

@daren-thomas if it works can you also check and merge?

**Comment by daren-thomas** [comment]
This breaks the demand graphs functionality (outputs pdf files with extension .html)

**Comment by JIMENOFONSECA** [comment]
Fixed, could you please check? merci

**Comment by daren-thomas** [comment]
great job!

**Pull request merged**
