### PR TITLE
Changes to reference case folder structure

### PR DESCRIPTION
**Pull request by JIMENOFONSECA**

### CODE REVIEW

**Comment by daren-thomas** [comment]
The radiation script is not running through:

```in CalcRadiation
Traceback (most recent call last):
  File "C:/Users/darthoma/Documents/GitHub/CEAforArcGIS/cea/test.py", line 12, in <module>
    radiation.test_solar_radiation()
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\radiation.py", line 484, in test_solar_radiation
    weather_path= weather_path)
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\radiation.py", line 110, in solar_radiation_vertical
    locator.get_temporary_folder(), aspect_slope, heightoffset, gv)
  File "C:\Users\darthoma\Documents\GitHub\CEAforArcGIS\cea\radiation.py", line 267, in CalcRadiation
    diffuseProp = str(T_G_day.loc[day - 1, 'diff'])
  File "C:\Users\darthoma\Anaconda2\envs\esri103\lib\site-packages\pandas\core\indexing.py", line 1018, in __getitem__
    return self._getitem_tuple(key)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\lib\site-packages\pandas\core\indexing.py", line 590, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\lib\site-packages\pandas\core\indexing.py", line 697, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\lib\site-packages\pandas\core\indexing.py", line 1144, in _getitem_axis
    self._has_valid_type(key, axis)
  File "C:\Users\darthoma\Anaconda2\envs\esri103\lib\site-packages\pandas\core\indexing.py", line 1124, in _has_valid_type
    error()
  File "C:\Users\darthoma\Anaconda2\envs\esri103\lib\site-packages\pandas\core\indexing.py", line 1111, in error
    (key, self.obj._get_axis_name(axis)))
KeyError: 'the label [0] is not in the [index]'
```

**Comment by JIMENOFONSECA** [comment]
@daren-thomas it works fine now, sorry about it. could you check and merge? thanks!

**Comment by daren-thomas** [comment]
image

I can't run the tests... The Problem seems to be this bit of code that got uncommented:

image

**Comment by daren-thomas** [comment]
(notice how PyCharm warns you about this... this is why it is important that we get rid of all the warnings in the files...)

**Comment by JIMENOFONSECA** [comment]
This is a problem of the demand script and inputs in the HVAC model. @gabriel-happle could you take a look? Probably a datapoint of solar or internal gains is infinite or null

**Comment by daren-thomas** [comment]
It is also a classic bug. Why was the `else` case removed?

**Comment by gabriel-happle** [comment]
the problem is that the temperature (t) in this case is lower than -100ºC or higher than 60ºC. This doesn't make sense. I think in this case it is not bad that the test did not succeed

**Comment by daren-thomas** [comment]
We should raise an error, then. Anyway. Can you reproduce the bug?

**Comment by JIMENOFONSECA** [comment]
yes it happened to me before. the way to debug it is to check the datapoint that where introduced to the HVAc model when it failed

**Comment by daren-thomas** [comment]
How come it did not happen when you tested it on your computer? Shouldn't we have exactly the same output since we are using exactly the same reference cases?

**Comment by gabriel-happle** [comment]
Hey @daren-thomas, there is a problem with the new radiation files. We will generate new ones and send them to you.
By the way: My pull request contains a debugged version of the` calc_hvac()`. We could use that one also for the master `calc_thermal_loads()`

**Comment by daren-thomas** [comment]
can you tell me when the radiation files are updated? I am using radiation files that I generated myself with the radiation script of the same version...

Could you push the new `calc_hvac()` function to this branch please?

**Comment by gabriel-happle** [comment]
Yes, I could. But that would probably modify the results. I don't know if we want that.

**Comment by daren-thomas** [comment]
Oh, I'm sorry, it seems I misunderstood your comment above - I thought you were advocating using the new debugged version of

**Comment by JIMENOFONSECA** [comment]
@gabriel-happle could you test the radiation file and demand in your machine?

**Comment by gabriel-happle** [comment]
Can.

**Comment by daren-thomas** [comment]
I keep getting MemoryError when running the radiation script...

**Comment by daren-thomas** [comment]
Apart from the `MemoryError` in the radiation script, this seems to be working just fine...

**Pull request merged**
