### PR TITLE
I412 dhc network path

### PR DESCRIPTION
**Pull request by martin-mosteiro**
Thermo-hydraulic modeling of district heating and cooling networks.

This function performs thermal and hydraulic calculation of a "well-defined" network, namely, the plant/consumer substations, piping routes and the pipe properties (length/diameter/heat transfer coefficient) are already specified. This model is valid for networks with a tree topology (i.e., no loops) with one or multiple plants, but requires the output from each plant to be pre-defined (at the moment, it is assumed all plants supply the same share of the total demand).

The function does the following: (i) calculate substation heat exchanger specification, (ii) import network edges and nodes (from either csv files or shapefiles), (iii) assign pipe properties, (iv) for each time step, calculate network temperatures, pressures, plant requirements and pressure losses.

This pull request solves issues #393 , #407 , #408 , #409 , #412 . @shanshanhsieh @martin-mosteiro

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi would you mind reviewing this Pull Request?

**Comment by BhargavaKrishnaSreepathi** [comment]
Hey @JIMENOFONSECA @daren-thomas , can you pass me the 'manual of how to check the pull request'.

**Comment by JIMENOFONSECA** [comment]
You may ask it to the authors of the pull request directly.

Best, Jimeno

On 10 Feb 2017, at 10:58, BhargavaKrishnaSreepathi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @JIMENOFONSECA<https://github.com/JIMENOFONSECA> @daren-thomas<https://github.com/daren-thomas> , can you pass me the 'manual of how to check the pull request'.

**Comment by BhargavaKrishnaSreepathi** [comment]
@shanshanhsieh @martin-mosteiro : can you let me know what is the output expected after these changes? and what are the results i need to look at to verify this request

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh in the mean time please solve the current conflicts of the branch...

**Comment by martin-mosteiro** [comment]
@JIMENOFONSECA @shanshanhsieh I took the liberty to solve the conflicts!
@BhargavaKrishnaSreepathi @shanshanhsieh probably makes sense to clarify this in person on Monday?

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi is this working in your computer? where should I start to test this? maybe a guide could help..

**Comment by BhargavaKrishnaSreepathi** [comment]
Hey @JIMENOFONSECA , I think it makes more sense to test this Pull request when the network optimization part is done. I am actually trying to figure out the procedure for optimization now

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi just for usability. It would be great to have this optimization working separately of the whole conversion system. The reason is that we can have this function activated if multiple network configurations want to be analyzed, before using the optimization of conversion systems.

**Comment by BhargavaKrishnaSreepathi** [comment]
@JIMENOFONSECA : Noted , Actually working on a structure similar to using 'multi-processing', where we can either use it or let the default setting run.

**Comment by JIMENOFONSECA** [comment]
@martin-mosteiro could you solve conflicts and create a readme.md in the folder to understand how to execute the work and test it? @daren-thomas does this need to be included in the dodo tests?

**Comment by daren-thomas** [comment]
yes, it should be included in the dodo tests. we need to formalize how to prove it is still working. also unit tests should be written. I guess I'll have to hold a talk on Test Driven Development someday...

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh is this ready to be merged?

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA  It is currently being reviewed by @BhargavaKrishnaSreepathi

**Comment by BhargavaKrishnaSreepathi** [comment]
@JIMENOFONSECA @shanshanhsieh : We have been working on this branch. Currently, Shanshan is simulating the thermal and pressure losses in Simulink. Once we have the estimated losses from Simulink, we will compare with the losses calculated from the network file generated by @shanshanhsieh and @martin-mosteiro. Hopefully this will be ready by next week to be merged

**Comment by JIMENOFONSECA** [comment]
@BhargavaKrishnaSreepathi closing this PR until ready. it would need to pass updates from the other branches first.

**Pull request closed without merging**
