### PR TITLE
I464 technology documentation

### PR DESCRIPTION
**Pull request by shanshanhsieh**
Documentation for most of the scripts in the resources and technologies forlders.
The unfinished parts require more information, it will be tackled in issue #478.

### CODE REVIEW

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh @daren-thomas some how the builds of this are failing, does it happen also when somebody changes the documentation?

**Comment by JIMENOFONSECA** [comment]
@shanshanhsieh please verify merging issues

**Comment by shanshanhsieh** [comment]
@JIMENOFONSECA the merging conflicts are solved, but I don't know how to solve the remaining failed check problem.

**Comment by JIMENOFONSECA** [comment]
Daren might shed some light on this
On 28 Feb 2017, at 9:43 am, shanshanhsieh <notifications@github.com<mailto:notifications@github.com>> wrote:


@JIMENOFONSECA<https://github.com/JIMENOFONSECA> the merging conflicts are solved, but I don't know how to solve the remaining failed check problem.

**Comment by daren-thomas** [comment]
I just ran the unittests for this branch and it seems the `storagetank` module requires the `globalvars.GlobalVariables` class to have a member called `Utank`. Either this was never in `gv` or it was removed long time ago, because I've been trying to find it and no success - maybe on another branch?

I see multiple branches starting with i464 - maybe one of them adds the functionality required?

**Comment by martin-mosteiro** [comment]
#464 is the documentation issue - in principle, none of the branches with that label should change the code functionality

**Pull request merged**
